from locust import HttpUser, task, between
import random

class TodoUser(HttpUser):
    # Tunggu antara 1 hingga 2 detik antar tugas (simulasi jeda manusia)
    wait_time = between(1, 2)
    
    # URL dasar akan diatur saat menjalankan Locust (misalnya http://167.99.1.234)

    @task(3) # Tugas ini akan dilakukan 3 kali lebih sering daripada tugas lain
    def load_main_page(self):
        """Simulasikan pengguna memuat halaman utama untuk melihat daftar tugas."""
        self.client.get("/", name="/") # name digunakan untuk pengelompokan laporan

    @task(1) # Tugas ini akan dilakukan 1 kali
    def add_new_task(self):
        """Simulasikan pengguna menambahkan tugas baru."""
        # Membuat tugas acak untuk menghindari duplikasi (jika app.py memerlukannya)
        task_title = f"Task generated by load test - {random.randint(1000, 9999)}"
        # Karena form Anda menggunakan method GET, kita mengirim task sebagai query parameter
        self.client.get(f"/addTask?task={task_title}", name="/addTask")