apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
spec:
  type: NodePort # <--- DIUBAH KE NODEPORT
  ports:
    - port: 5000
      targetPort: 8000
      protocol: TCP
  selector:
    app: todo-app
